routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

use App\Http\Controllers\ItemController;


Route::resource('itemkategori', 'ItemKategoriController');
Route::resource('userrole', 'UserRoleController');
Route::resource('item','ItemController');
Route::resource('user', 'UserController');
Route::resource('transaksi_list', 'TransaksiListController');

Route::get('/transaksi', 'TransaksiController@createTransaksi')->name('create_transaksi');

Route::post('/transaksi', 'TransaksiController@getItem')->name('get_item_transaksi');

Route::post('/transaksi/store', 'TransaksiController@storeTransaksi')->name('store_transaksi');

Route::get('/transaksi/list', 'TransaksiController@index');
Route::get('/transaksi/list/{id}', 'TransaksiController@show');
Route::get('/transaksi/list/{id}/edit', 'TransaksiController@edit');
Route::delete('/transaksi/list/{id}', 'TransaksiController@destroy');

Route::get('/transaksi/list/{id}/detail','TransaksiController@detail');
Route::get('/transaksi/list/{id}/cetak','TransaksiController@cetak');
Route::get('/dashboard', 'DashboardController@count');


//Route::get('/dashboard', function () {
//    return view('dashboard');

//});

app/ItemKategori.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Eloquent;
class ItemKategori extends Model
{
    protected $table = "item_kategori";

    protected $fillable = ['nama','is_deleted'];

    public function item()
    {
        return $this->hasMany('App\Models\Item');
    }
}

app/Http/Controllers/ItemKategoriController.php
<?php

namespace App\Http\Controllers;

use App\ItemKategori;
use Illuminate\Http\Request;

class ItemKategoriController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    function index(){
        //$pertanyaan = DB::table('pertanyaan')->get();

        //eloquent
        $item_kategori=ItemKategori::all();
        return view('item_kategori.index', compact('item_kategori'));
    }

    function create(){

        return view('item_kategori.create');
    }

    function store(Request $request){
        $request->validate([
            'nama' => 'required|unique:item_kategori',
        ]);

        $item_kategori=ItemKategori::create(['nama' => $request["nama"]]);

        return redirect('/itemkategori');
    }

    function show($id){
        //$pertanyaan = DB::table('pertanyaan')->where('id', $pertanyaan_id)->first();
        $item_kategori = ItemKategori::find($id);

        return view('item_kategori.show', compact('item_kategori'));
    }

    function edit($id){
        $item_kategori = ItemKategori::find($id);
        return view('item_kategori.edit', compact('item_kategori'));
    }

    function update($id, Request $request){
        $request->validate([
            'nama' => 'required',
        ]);
        //mass update
        ItemKategori::where('id', $id)
          ->update(['nama' =>  $request["nama"],
                    ]);


        // $query = DB::table('pertanyaan')
        //     ->where('id',$pertanyaan_id)
        //     ->update([
        //     "judul" => $request["judul"],
        //     "isi" => $request["isi"],
        //     "tanggal_diperbaharui" => date("Y-m-d")
        // ]);
        return redirect('/itemkategori');
    }

    function destroy($id){
        //$query = DB::table('pertanyaan')->where('id', $pertanyaan_id)->delete();
        //deleteing an existing model on key

        ItemKategori::destroy($id);

        return redirect('/itemkategori');
    }

}

resources/views/item_kategori/create.blade.php
@extends('layouts.master')

@push('css')
<style type="text/css">
    .btn{
        margin-right: 2px;margin-left: 2px;
    }
 </style>
@endpush


@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h4>Tambah Item Kategori</h4>
                </div>
                <form action="{{route('itemkategori.store')}}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" name="nama" id="nama" placeholder="Masukkan Nama Item Kategori">
                        @error('judul')
                            <div class="alert alert-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Tambah</button>
                </form>

            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')

@endpush

resources/views/item_kategori/edit.blade.php
@extends('layouts.master')

@push('css')
<style type="text/css">
    .btn{
        margin-right: 2px;margin-left: 2px;
    }
 </style>
@endpush


@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h4>Ubah Item Kategori</h4>
                </div>
                <form action="{{route('itemkategori.update',['itemkategori'=>$item_kategori->id])}}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="title">Nama</label>
                        <input type="text" class="form-control" name="nama" value="{{$item_kategori->nama}}" id="isi" placeholder="Masukkan Nama Item Kategori">
                        @error('title')
                            <div class="alert alert-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Edit</button>
                </form>

            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')

@endpush

resources/views/item_kategori/index.blade.php
@extends('layouts.master')

@push('css')
<style type="text/css">
    .btn{
        margin-right: 2px;margin-left: 2px;
    }
 </style>
@endpush


@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h4>Item Kategori</h4>

                </div>
            <div> <a href="{{ route('itemkategori.create')}}" class="btn btn-primary">Tambah</a></div>
                <h6 class="card-subtitle">&nbsp;</h6>
                <div class="table-responsive">
                    <table id="zero_config" class="table table-striped table-bordered no-wrap">
                        <thead class="bg-info text-white">
                            <tr>
                                <th style="width: 10%">No</th>
                                <th style="width: 70%%">Nama</th>
                                <th style="width: 20%">Action</th>

                            </tr>
                        </thead>
                        <tbody class="border boder-info">
                            @forelse ($item_kategori as $key=>$value)
                            <tr>
                                <td>{{$key + 1}}</th>
                                <td>{{$value->nama}}</td>
                                <td style="display:flex;">

                                    <a href="{{route('itemkategori.show',['itemkategori'=>$value->id])}}" class="btn waves-effect waves-light btn-info">Show</a>
                                    <a href="{{route('itemkategori.edit',['itemkategori'=>$value->id])}}" class="btn waves-effect waves-light btn-warning">Edit</a>
                                    <form action="{{route('itemkategori.destroy',['itemkategori'=>$value->id])}}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <input type="submit" class="btn waves-effect waves-light btn-danger" value="Delete">
                                    </form>
                                </td>
                            </tr>
                        @empty
                            <tr colspan="3">
                                <td colspan="3" align="center">No data</td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    $('#zero_config').DataTable();
</script>
@endpush

resources/views/item_kategori/show.blade.php
@extends('layouts.master')

@push('css')
<style type="text/css">
    .btn{
        margin-right: 2px;margin-left: 2px;
    }
 </style>
@endpush


@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h4>Detail Item Kategori</h4>
                </div>
                <table>
                    <tr>
                        <td>Nama Item Kategori
                        </td>
                        <td>:
                        </td>
                        <td>{{$item_kategori->nama}}
                        </td>
                    </tr>
                    <tr>
                        <td>Dibuat Tanggal
                        </td>
                        <td>:
                        </td>
                        <td>{{$item_kategori->created_at}}
                        </td>
                    </tr>
                    <tr>
                        <td>Diubah Tanggal
                        </td>
                        <td>:
                        </td>
                        <td>{{$item_kategori->updated_at}}
                        </td>
                    </tr>
                </table>
                <br><br>
                <div> <a href="{{ route('itemkategori.index')}}" class="btn btn-primary">Back</a></div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')

@endpush