routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

use App\Http\Controllers\ItemController;


Route::resource('itemkategori', 'ItemKategoriController');
Route::resource('userrole', 'UserRoleController');
Route::resource('item','ItemController');
Route::resource('user', 'UserController');
Route::resource('transaksi_list', 'TransaksiListController');

Route::get('/transaksi', 'TransaksiController@createTransaksi')->name('create_transaksi');

Route::post('/transaksi', 'TransaksiController@getItem')->name('get_item_transaksi');

Route::post('/transaksi/store', 'TransaksiController@storeTransaksi')->name('store_transaksi');

Route::get('/transaksi/list', 'TransaksiController@index');
Route::get('/transaksi/list/{id}', 'TransaksiController@show');
Route::get('/transaksi/list/{id}/edit', 'TransaksiController@edit');
Route::delete('/transaksi/list/{id}', 'TransaksiController@destroy');

Route::get('/transaksi/list/{id}/detail','TransaksiController@detail');
Route::get('/transaksi/list/{id}/cetak','TransaksiController@cetak');
Route::get('/dashboard', 'DashboardController@count');


//Route::get('/dashboard', function () {
//    return view('dashboard');

//});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;
    protected $table= "users";
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function UserRole()
    {
        return $this->belongsTo('App\Models\UserRole');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use App\User;
use App\UserRole;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use DB;
use Illuminate\Support\Facades\Hash;
class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    //
    function index()
    {
        $user=User::all();

        $user=DB::table('users')
        ->select('users.id as id','users.name as name','users.password as password','users.email as email','users.role_id as user_role_id', 'user_role.id as user_role_id','user_role.nama as user_role_nama')
        ->join('user_role','user_role.id','=','users.role_id')
        ->get();
        return view('user.index', compact('user'));
    }
    function create()
    {
        $user_role=UserRole::all();

        return view('user.create',compact('user_role'));
    }
    function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required',
            'password'=>'required',
            'role_id'=>'required'
        ]);
        $user=User::create([
            'name' => $request["name"],
            'email'=> $request["email"],
            'password'=>Hash::make($request['password']),
            'role_id'=>$request["role_id"]
            ]);
        return redirect('/user');
    }
    function show($id)
    {
        $user = User::find($id);

        return view('user.show', compact('user'));
    }

    function edit($id)
    {
        $user = User::find($id);
        $user_role=UserRole::all();
        return view('user.edit', compact('user','user_role'));
    }

    function update($id, Request $request)
    {
        $request->validate([
            'name' => 'required',
            'email' => 'required',
            'password'=>'required',
            'role_id'=>'required'
        ]);
        User::find($id)->update([
            'name' => $request["name"],
            'email'=> $request["email"],
            'password'=>Hash::make($request['password']),
            'role_id'=>$request["role_id"]
            ]);
        return redirect('/user');
    }

    function destroy($id)
    {
        User::destroy($id);
        return redirect('/user');
    }
}

resources/views/user/create.blade.php
@extends('layouts.master')

@push('css')
<style type="text/css">
    .btn{
        margin-right: 2px;margin-left: 2px;
    }
 </style>
@endpush


@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h4>Tambah Data User</h4>
                </div>
                <form action="{{route('user.store')}}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="title">Nama User</label>
                        <input type="text" class="form-control" name="name" id="name" placeholder="Masukkan Nama User">
                        <label for="title">Email User</label>
                        <input type="text" class="form-control" name="email" id="email" placeholder="Masukkan Email User">
                        <label for="title">Password</label>
                        <input type="text" class="form-control" name="password" id="password" placeholder="Masukkan Password User">
                        <label for="title">Role User</label>
                        <select class="custom-select" id="role_id" name="role_id" >
                            <option value=""> --Silahkan Pilih-- </option>
                            @foreach ($user_role as $value)
                                  <option value="{{ $value->id }}">{{ $value->nama }}</option>
                            @endforeach
                       </select>
                        
                        @error('title')
                            <div class="alert alert-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')

@endpush

resources/views/user/edit.blade.php
@extends('layouts.master')

@push('css')
<style type="text/css">
    .btn{
        margin-right: 2px;margin-left: 2px;
    }
 </style>
@endpush


@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h4>Edit Data User</h4>
                </div>
                <form action="{{route('user.update', ['user'=>$user->id])}}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="title">Nama User</label>
                        <input type="text" class="form-control" value="{{$user->name}}" name="name" id="name" placeholder="Masukkan Nama User Baru">
                        <label for="title">Email User</label>
                        <input type="text" class="form-control" value="{{$user->email}}" name="email" id="email" placeholder="Masukkan Email User Baru">

                        <label for="title">Password</label>
                        <input type="text" class="form-control" name="password" id="password" placeholder="Masukkan Password User">
                        <label for="title">Role User</label>
                        <select class="custom-select" id="role_id" name="role_id">
                            <option value=""> --Silahkan Pilih-- </option>
                            @foreach ($user_role as $value)
                                    @if($value->id ==$user->role_id)
                                    <option value="{{ $value->id }}" selected>{{ $value->nama }}</option>
                                     @else
                                            <option value="{{ $value->id }}">{{ $value->nama }}</option>
                                 @endif

                            @endforeach
                       </select>

                        @error('judul')
                            <div class="alert alert-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Tambah</button>
                </form>

            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')

@endpush

resources/views/user/index.blade.php
@extends('layouts.master')

@push('css')
<style type="text/css">
    .btn{
        margin-right: 2px;margin-left: 2px;
    }
 </style>
@endpush


@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h4>User</h4>

                </div>
            <div> <a href="{{ route('user.create')}}" class="btn btn-primary">Tambah</a></div>
                <h6 class="card-subtitle">&nbsp;</h6>
                <div class="table-responsive">
                    <table id="zero_config" class="table table-striped table-bordered no-wrap">
                        <thead class="bg-info text-white">
                            <tr>
                                <th style="width: 10%">No</th>
                                <th style="width: 70%%">Nama</th>
                                <th style="width: 70%%">Email</th>
                                <th style="width: 20%">Action</th>

                            </tr>
                        </thead>
                        <tbody class="border boder-info">
                            @forelse ($user as $key=>$value)
                            <tr>
                                <td>{{$key + 1}}</th>
                                <td>{{$value->name}}</td>
                                <td>{{$value->email}}</td>
                                <td style="display:flex;">

                                    <a href="{{route('user.show',['user'=>$value->id])}}" class="btn waves-effect waves-light btn-info">Show</a>
                                    <a href="{{route('user.edit',['user'=>$value->id])}}" class="btn waves-effect waves-light btn-warning">Edit</a>
                                    <form action="{{route('user.destroy',['user'=>$value->id])}}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <input type="submit" class="btn waves-effect waves-light btn-danger" value="Delete">
                                    </form>
                                </td>
                            </tr>
                        @empty
                            <tr colspan="4">
                                <td colspan="4" align="center">No data</td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    $('#zero_config').DataTable();
</script>
@endpush

resources/views/user/show.blade.php
@extends('layouts.master')

@push('css')
<style type="text/css">
    .btn{
        margin-right: 2px;margin-left: 2px;
    }
 </style>
@endpush


@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h4>Detail User</h4>
                </div>
                <table>
                    <tr>
                        <td>Nama User
                        </td>
                        <td>:
                        </td>
                        <td>{{$user->name}}
                        </td>
                    </tr>
                    <tr>
                        <td>Email User
                        </td>
                        <td>:
                        </td>
                        <td>{{$user->email}}
                        </td>
                    </tr>
                    <tr>
                        <td>Dibuat Tanggal
                        </td>
                        <td>:
                        </td>
                        <td>{{$user->created_at}}
                        </td>
                    </tr>
                    <tr>
                        <td>Diubah Tanggal
                        </td>
                        <td>:
                        </td>
                        <td>{{$user->updated_at}}
                        </td>
                    </tr>
                </table>
                <br><br>
                <div> <a href="{{ route('user.index')}}" class="btn btn-primary">Back</a></div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')

@endpush