routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

use App\Http\Controllers\ItemController;


Route::resource('itemkategori', 'ItemKategoriController');
Route::resource('userrole', 'UserRoleController');
Route::resource('item','ItemController');
Route::resource('user', 'UserController');
Route::resource('transaksi_list', 'TransaksiListController');

Route::get('/transaksi', 'TransaksiController@createTransaksi')->name('create_transaksi');

Route::post('/transaksi', 'TransaksiController@getItem')->name('get_item_transaksi');

Route::post('/transaksi/store', 'TransaksiController@storeTransaksi')->name('store_transaksi');

Route::get('/transaksi/list', 'TransaksiController@index');
Route::get('/transaksi/list/{id}', 'TransaksiController@show');
Route::get('/transaksi/list/{id}/edit', 'TransaksiController@edit');
Route::delete('/transaksi/list/{id}', 'TransaksiController@destroy');

Route::get('/transaksi/list/{id}/detail','TransaksiController@detail');
Route::get('/transaksi/list/{id}/cetak','TransaksiController@cetak');
Route::get('/dashboard', 'DashboardController@count');


//Route::get('/dashboard', function () {
//    return view('dashboard');

//});

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Eloquent;

class Item extends Model
{
    //
    protected $table = "item";
    protected $fillable = ["nama", "harga", "item_kategori"];

    public function ItemKategori()
    {
        return $this->belongsTo('App\Models\ItemKategori');
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;
use App\Item;
use App\ItemKategori;
use Illuminate\Http\Request;
use DB;

class ItemController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        //
        //$item=Item::all();

        //$item= Item::with('ItemKategori')->get();
        $item=DB::table('item')
        ->select('item.id as id','item.nama as nama','item.harga as harga','item.item_kategori as item_kategori_id','item_kategori.nama as item_kategori_nama')
        ->join('item_kategori','item_kategori.id','=','item.item_kategori')
        ->get();

        return view("items.index", compact('item'));
    }


    public function create()
    {
        $item_kategori=ItemKategori::all();

        return view('items.create', compact('item_kategori'));
    }

     function store(Request $request)
    {
        //
        $request->validate([
                'nama' => 'required',
                'harga' => 'required',
                'item_kategori' => 'required'
        ]);
        $item=Item::create([
            'nama' => $request["nama"],
            'harga'=>$request["harga"],
            'item_kategori' => $request["item_kategori"]
        ]);
        return redirect('/item');

    }

     function show($id)
    {
        //
        $item = Item::find($id);
        return view('items.show', compact('item'));
    }


    public function edit($id)
    {
        //
        $item = Item::find($id);
        $item_kategori=ItemKategori::all();
        return view('items.edit', compact('item','item_kategori'));
    }


    public function update(Request $request, $id)
    {

         $request->validate([
             'nama' => 'required',
             'harga' => 'required',
             'item_kategori' => 'required'
         ]);

        Item::where('id', $id)
            ->update([
            'nama' => $request["nama"],
            'harga'=>$request["harga"],
            'item_kategori' => $request["item_kategori"]
        ]);

        return redirect('/item');
    }

     function destroy($id)
    {
        //
        Item::destroy($id);
        return redirect('/item');
    }
}

resources/views/items/create.blade.php
@extends('layouts.master')

@push('css')
<style type="text/css">
    .btn{
        margin-right: 2px;margin-left: 2px;
    }
 </style>
@endpush


@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h4>Tambah Item</h4>
                </div>
                <form action="{{route('item.store')}}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="title">Nama</label>
                        <input type="text" class="form-control" name="nama"   id="isi" placeholder="Masukkan Nama Item">
                        <label for="title">Harga</label>
                        <input type="number" class="form-control" name="harga" id="isi" placeholder="Masukkan Harga Item">
                        <label for="title">Kategori Item</label>
                        <select class="custom-select" id="item_kategori" name="item_kategori" id="item_kategori">
                            <option value=""> --Silahkan Pilih-- </option>
                             @foreach ($item_kategori as $value)
                                   <option value="{{ $value->id }}">{{ $value->nama }}</option>
                             @endforeach
                        </select>
                        @error('title')
                            <div class="alert alert-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Tambah</button>
                </form>

            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')

@endpush

resources/views/items/edit.blade.php
@extends('layouts.master')

@push('css')
<style type="text/css">
    .btn{
        margin-right: 2px;margin-left: 2px;
    }
 </style>
@endpush


@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h4>Ubah Item</h4>
                </div>
                <form action="{{route('item.update',['item'=>$item->id])}}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="title">Nama</label>
                        <input type="text" class="form-control" name="nama" value="{{$item->nama}}" id="isi" placeholder="Masukkan Nama Item">
                        <label for="title">Harga</label>
                        <input type="text" class="form-control" name="harga" value="{{$item->harga}}" id="isi" placeholder="Masukkan Harga Item">
                        <label for="title">Kategori Item</label>
                        <select class="custom-select" id="item_kategori" name="item_kategori" id="item_kategori">
                             @foreach ($item_kategori as $value)
                             @if($value->id ==$item->kategori_id)
                                   <option value="{{ $value->id }}" selected>{{ $value->nama }}</option>
                             @else
                                    <option value="{{ $value->id }}">{{ $value->nama }}</option>
                             @endif
                             @endforeach
                        </select>
                        @error('title')
                            <div class="alert alert-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Edit</button>
                </form>

            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')

@endpush

resources/views/items/index.blade.php
@extends('layouts.master')

@push('css')
<style type="text/css">
    .btn{
        margin-right: 2px;margin-left: 2px;
    }
 </style>
@endpush


@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h4>Item</h4>

                </div>
            <div> <a href="{{ route('item.create')}}" class="btn btn-primary">Tambah</a></div>
                <h6 class="card-subtitle">&nbsp;</h6>
                <div class="table-responsive">
                    <table id="zero_config" class="table table-striped table-bordered no-wrap">
                        <thead class="bg-info text-white">
                            <tr>
                                <th style="width: 10%">No</th>
                                <th style="width: 70%%">Nama</th>
                                <th style="width: 20%">Harga</th>
                                <th style="width: 20%">Kategori Item</th>
                                <th style="width: 20%">Action</th>
                            </tr>
                        </thead>
                        <tbody class="border boder-info">
                            @forelse ($item as $key=>$value)
                            <tr>
                                <td>{{$key + 1}}</th>
                                <td>{{$value->nama}}</td>
                                <td>{{$value->harga}}</td>
                                <td>{{$value->item_kategori_nama}}</td>
                                <td style="display:flex;">

                                    <a href="{{route('item.show',['item'=>$value->id])}}" class="btn waves-effect waves-light btn-info">Show</a>
                                    <a href="{{route('item.edit',['item'=>$value->id])}}" class="btn waves-effect waves-light btn-warning">Edit</a>
                                    <form action="{{route('item.destroy',['item'=>$value->id])}}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <input type="submit" class="btn waves-effect waves-light btn-danger" value="Delete">
                                    </form>
                                </td>
                            </tr>
                        @empty
                            <tr colspan="3">
                                <td colspan="5" align="center">No data</td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    $('#zero_config').DataTable();
</script>
@endpush

resources/views/items/show.blade.php
@extends('layouts.master')

@push('css')
<style type="text/css">
    .btn{
        margin-right: 2px;margin-left: 2px;
    }
 </style>
@endpush


@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h4>Detail Item</h4>
                </div>
                <table>
                    <tr>
                        <td>Nama Item
                        </td>
                        <td>:
                        </td>
                        <td>{{$item->nama}}
                        </td>
                    </tr>
                    <tr>
                        <td>Harga
                        </td>
                        <td>:
                        </td>
                        <td>{{$item->harga}}
                        </td>
                    </tr>
                    <tr>
                        <td>Kategori Item
                        </td>
                        <td>:
                        </td>
                        <td>{{$item->item_kategori}}
                        </td>
                    </tr>
                    <tr>
                        <td>Dibuat Tanggal
                        </td>
                        <td>:
                        </td>
                        <td>{{$item->created_at}}
                        </td>
                    </tr>
                    <tr>
                        <td>Diubah Tanggal
                        </td>
                        <td>:
                        </td>
                        <td>{{$item->updated_at}}
                        </td>
                    </tr>
                </table>
                <br><br>
                <div> <a href="{{ route('item.index')}}" class="btn btn-primary">Back</a></div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')

@endpush