routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

use App\Http\Controllers\ItemController;


Route::resource('itemkategori', 'ItemKategoriController');
Route::resource('userrole', 'UserRoleController');
Route::resource('item','ItemController');
Route::resource('user', 'UserController');
Route::resource('transaksi_list', 'TransaksiListController');

Route::get('/transaksi', 'TransaksiController@createTransaksi')->name('create_transaksi');

Route::post('/transaksi', 'TransaksiController@getItem')->name('get_item_transaksi');

Route::post('/transaksi/store', 'TransaksiController@storeTransaksi')->name('store_transaksi');

Route::get('/transaksi/list', 'TransaksiController@index');
Route::get('/transaksi/list/{id}', 'TransaksiController@show');
Route::get('/transaksi/list/{id}/edit', 'TransaksiController@edit');
Route::delete('/transaksi/list/{id}', 'TransaksiController@destroy');

Route::get('/transaksi/list/{id}/detail','TransaksiController@detail');
Route::get('/transaksi/list/{id}/cetak','TransaksiController@cetak');
Route::get('/dashboard', 'DashboardController@count');


//Route::get('/dashboard', function () {
//    return view('dashboard');

//});

app/UserRole.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserRole extends Model
{
    protected $table = "user_role";

    protected $fillable = ['nama','is_deleted'];
}

app/Http/Controllers/UserRoleController.php
<?php

namespace App\Http\Controllers;

use App\UserRole;
use Illuminate\Http\Request;

class UserRoleController extends Controller
{
    //
    public function __construct()
    {
        $this->middleware('auth');
    }
    function index(){
        //$pertanyaan = DB::table('pertanyaan')->get();

        //eloquent
        $user_role=UserRole::all();
        return view('user_role.index', compact('user_role'));
    }

    function create(){

        return view('user_role.create');
    }

    function store(Request $request){
        $request->validate([
            'nama' => 'required|unique:user_role',
        ]);

        $user_role=UserRole::create(['nama' => $request["nama"]]);

        return redirect('/userrole');
    }

    function show($id){
        //$pertanyaan = DB::table('pertanyaan')->where('id', $pertanyaan_id)->first();
        $user_role = UserRole::find($id);

        return view('user_role.show', compact('user_role'));
    }

    function edit($id){
        $user_role = UserRole::find($id);
        return view('user_role.edit', compact('user_role'));
    }

    function update($id, Request $request){
        $request->validate([
            'nama' => 'required',
        ]);
        //mass update
        UserRole::where('id', $id)
          ->update(['nama' =>  $request["nama"],
                    ]);


        // $query = DB::table('pertanyaan')
        //     ->where('id',$pertanyaan_id)
        //     ->update([
        //     "judul" => $request["judul"],
        //     "isi" => $request["isi"],
        //     "tanggal_diperbaharui" => date("Y-m-d")
        // ]);
        return redirect('/userrole');
    }

    function destroy($id){
        //$query = DB::table('pertanyaan')->where('id', $pertanyaan_id)->delete();
        //deleteing an existing model on key

        UserRole::destroy($id);

        return redirect('/userrole');
    }
}

resources/views/user_role/create.blade.php
@extends('layouts.master')

@push('css')
<style type="text/css">
    .btn{
        margin-right: 2px;margin-left: 2px;
    }
 </style>
@endpush


@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h4>Tambah Item Kategori</h4>
                </div>
                <form action="{{route('userrole.store')}}" method="POST">
                    @csrf
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control" name="nama" id="nama" placeholder="Masukkan Nama User Role">
                        @error('judul')
                            <div class="alert alert-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Tambah</button>
                </form>

            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')

@endpush

resources/views/user_role/edit.blade.php
@extends('layouts.master')

@push('css')
<style type="text/css">
    .btn{
        margin-right: 2px;margin-left: 2px;
    }
 </style>
@endpush


@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h4>Ubah User Role</h4>
                </div>
                <form action="{{route('userrole.update',['userrole'=>$user_role->id])}}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="title">Nama</label>
                        <input type="text" class="form-control" name="nama" value="{{$user_role->nama}}" id="isi" placeholder="Masukkan Nama User Role">
                        @error('title')
                            <div class="alert alert-danger">
                                {{ $message }}
                            </div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Edit</button>
                </form>

            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')

@endpush

resources/views/user_role/index.blade.php
@extends('layouts.master')

@push('css')
<style type="text/css">
    .btn{
        margin-right: 2px;margin-left: 2px;
    }
 </style>
@endpush


@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h4>User Role</h4>

                </div>
            <div> <a href="{{ route('userrole.create')}}" class="btn btn-primary">Tambah</a></div>
                <h6 class="card-subtitle">&nbsp;</h6>
                <div class="table-responsive">
                    <table id="zero_config" class="table table-striped table-bordered no-wrap">
                        <thead class="bg-info text-white">
                            <tr>
                                <th style="width: 10%">No</th>
                                <th style="width: 70%%">Nama</th>
                                <th style="width: 20%">Action</th>

                            </tr>
                        </thead>
                        <tbody class="border boder-info">
                            @forelse ($user_role as $key=>$value)
                            <tr>
                                <td>{{$key + 1}}</th>
                                <td>{{$value->nama}}</td>
                                <td style="display:flex;">

                                    <a href="{{route('userrole.show',['userrole'=>$value->id])}}" class="btn waves-effect waves-light btn-info">Show</a>
                                    <a href="{{route('userrole.edit',['userrole'=>$value->id])}}" class="btn waves-effect waves-light btn-warning">Edit</a>
                                    <form action="{{route('userrole.destroy',['userrole'=>$value->id])}}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <input type="submit" class="btn waves-effect waves-light btn-danger" value="Delete">
                                    </form>
                                </td>
                            </tr>
                        @empty
                            <tr colspan="3">
                                <td colspan="3" align="center">No data</td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
    $('#zero_config').DataTable();
</script>
@endpush

resources/views/user_role/show.blade.php
@extends('layouts.master')

@push('css')
<style type="text/css">
    .btn{
        margin-right: 2px;margin-left: 2px;
    }
 </style>
@endpush


@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h4>Detail User Role</h4>
                </div>
                <table>
                    <tr>
                        <td>Nama User Role
                        </td>
                        <td>:
                        </td>
                        <td>{{$user_role->nama}}
                        </td>
                    </tr>
                    <tr>
                        <td>Dibuat Tanggal
                        </td>
                        <td>:
                        </td>
                        <td>{{$user_role->created_at}}
                        </td>
                    </tr>
                    <tr>
                        <td>Diubah Tanggal
                        </td>
                        <td>:
                        </td>
                        <td>{{$user_role->updated_at}}
                        </td>
                    </tr>
                </table>
                <br><br>
                <div> <a href="{{ route('userrole.index')}}" class="btn btn-primary">Back</a></div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')

@endpush